# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    ports:
      - "7000:5432"
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root